// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0HvQuakQDoBFpxlzh1CQtClKwYlwYeaE',
    appId: '1:838884683449:web:e94ff5834690128fc9b568',
    messagingSenderId: '838884683449',
    projectId: 'rentify-bc9b7',
    authDomain: 'rentify-bc9b7.firebaseapp.com',
    storageBucket: 'rentify-bc9b7.firebasestorage.app',
    measurementId: 'G-5LFHGGCBZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHCdy8-ZcIgt1UfXJsIp3QU7ky8mXd4IE',
    appId: '1:838884683449:android:4a1aad3cf7ba3241c9b568',
    messagingSenderId: '838884683449',
    projectId: 'rentify-bc9b7',
    storageBucket: 'rentify-bc9b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKNDE9eaVGy2BzLknLDuLFk3Jj_aSVUw0',
    appId: '1:838884683449:ios:016ce8c53f99ecf2c9b568',
    messagingSenderId: '838884683449',
    projectId: 'rentify-bc9b7',
    storageBucket: 'rentify-bc9b7.firebasestorage.app',
    iosBundleId: 'com.example.rentify',
  );

}